language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
install:
  - dzil authordeps --missing | cpanm
  - dzil listdeps --missing | cpanm
script:
  - dzil test --author --release
